# Generated by Django 5.2.11 on 2026-02-24 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100)),
                ('transaction_amount', models.FloatField()),
                ('transaction_currency', models.CharField(max_length=10)),
                ('transaction_type', models.CharField(max_length=10)),
                ('transaction_timestamp', models.DateTimeField(auto_now_add=True)),
                ('transaction_is_fraud', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='frauddetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('model_accuracy', models.FloatField()),
                ('model_precision', models.FloatField()),
                ('model_recall', models.FloatField()),
                ('model_f1_score', models.FloatField()),
                ('model_timestamp', models.DateTimeField(auto_now_add=True)),
                ('model_is_fraud', models.BooleanField(default=False)),
                ('model_prediction', models.BooleanField(default=False)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fraud_management.transaction')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fraud_management.user'),
        ),
    ]
